export const ADD_USER = 'ADD_USER';
export const ADD_ASSIGNMENTS = 'ADD_ASSIGNMENTS';
export const ADD_ASSIGNMENT_TYPES = 'ADD_ASSIGNMENT_TYPES';
export const ADD_ASSIGNMENT_DETAILS = 'ADD_ASSIGNMENT_DETAILS';
export const ADD_PENDING_SUBJECTS = 'ADD_PENDING_SUBJECTS';
export const ADD_PENDING_ASSIGNMENTS = 'ADD_PENDING_ASSIGNMENTS';
export const ADD_GOALS = 'ADD_GOALS';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const ADD_SUBJECT_DETAILS = 'ADD_SUBJECT_DETAILS';
export const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS';

export const SET_SUBJECT = 'SET_SUBJECT';
export const ADD_META = 'ADD_META';
export const ADD_GOAL_TOUR = 'ADD_GOAL_TOUR';
export const ADD_ASSIGNMENT_TOUR = 'ADD_ASSIGNMENT_TOUR';
export const ADD_TODAY_ASSIGNMENTS = 'ADD_TODAY_ASSIGNMENTS';
export const STEP_COUNTER = 'STEP_COUNTER';

export const GOAL_TOUR_COUNTER = 'GOAL_TOUR_COUNTER';
export const HOME_TOUR_COUNTER = 'HOME_TOUR_COUNTER';

export const ADD_HOME_FILTERS = 'ADD_HOME_FILTERS';
